version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: WmMarketoProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.testgit.integrations:test123
  packages:
  - name: TestGitProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
